### ISSUE TITLE
Implement "Next" button that would allow the next post to be viewed

### ISSUE THREAD

**Issue by AlexanderDavid** [creesch/readReddit#2]
When reading all of the TIFUs I normally go post by post reading each one. It would be nice to be able to just hit a next button (maybe above the "done" button) and jump to the next post

**Comment by creesch** [comment]
Interesting idea, a bit tricky to implement. 

- For your use case I suppose the extension needs to assume that you are browsing the subreddit and not say your frontpage? 
- Should it fetch the current subreddit listing when you open the first story or check when you click next? 
- Should it first go the new post (and reload the entire page) or should it remain on the current page and simply load the next story into the overlay?

**Comment by AlexanderDavid** [comment]
I'm thinking this would be a specific use case when using the extension from the "overlay" text post rather than clicking straight through to the post. The URL still says that you would be on reddit.com/r/tifu for example so I imagine that all of the post URLs are still loaded in the DOM so you wouldn't have to reload anything. I would also say that it shouldn't reload but rather it should update the currently loaded page.

Currently, I am a busy college student who has no idea how extensions work but I am totally willing to take a crack at this if you can point me in the right direction and you think this is a valid feature for your app.

**Comment by creesch** [comment]
This has been implemented with 3f834d5 

All links leading to posts or comments on reddit will now be opened in the overlay by default.
